### ISSUE TITLE
Will removing the E = rmTaxa(names=1:3, alignment=D); from jcCoalescent.lphy has any further effect on generated XML and future analysis?

### ISSUE THREAD

**Issue by CSTE7007** [LinguaPhylo/LPhyBeast#158]
From the documentation [LPhyBEAST usage](https://linguaphylo.github.io/setup/#lphybeast-usage) section 

> ```
> cd $LPHY_PATH/examples/coalescent/
> $BEAST_PATH/bin/lphybeast -r 5 jcCoalescent.lphy
> ```
Running the code with latest [lphybeast](https://raw.githubusercontent.com/LinguaPhylo/LPhyBeast/master/lphybeast/bin/lphybeast) file placed inside `beast/bin/` directory throws an exception 
```
picocli.CommandLine$PicocliException:

Cannot find the mapping for given LPhy code to BEAST2 classes!
Input file = /home/user/lphy-studio-1.6.0/examples/coalescent/jcCoalescent.lphy
Please ensure you have installed the required LPhyBEAST extensions and BEAST2 packages :

Unhandled generator in generatorToBEAST(): class lphy.base.function.alignment.RemoveTaxa
        at lphybeast.LPhyBeastCMD.call(LPhyBeastCMD.java:169)
        at lphybeast.LPhyBeastCMD.call(LPhyBeastCMD.java:13)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at lphybeast.LPhyBeastCMD.main(LPhyBeastCMD.java:120)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at beastfx.app.tools.AppLauncher.runAppFromCMD(Unknown Source)
        at beastfx.app.tools.AppLauncher.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
        at beast.pkgmgmt.launcher.AppLauncherLauncher.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Unhandled generator in generatorToBEAST(): class lphy.base.function.alignment.RemoveTaxa
        at lphybeast.BEASTContext.generatorToBEAST(BEASTContext.java:738)
        at lphybeast.BEASTContext.traverseBEASTGeneratorObjects(BEASTContext.java:693)
        at lphybeast.BEASTContext.createBEASTObjects(BEASTContext.java:644)
        at lphybeast.BEASTContext.toBEASTXML(BEASTContext.java:162)
        at lphybeast.LPhyBeast.dictToBEASTXML(LPhyBeast.java:329)
        at lphybeast.LPhyBeast.writeXMLFrom(LPhyBeast.java:287)
        at lphybeast.LPhyBeast.run(LPhyBeast.java:102)
        at lphybeast.LPhyBeast.run(LPhyBeast.java:81)
        at lphybeast.LPhyBeastCMD.call(LPhyBeastCMD.java:160)
        ... 22 more
Oct 01, 2024 10:02:41 PM lphybeast.LPhyBeastCMD main
SEVERE: LPhyBEAST does not exit normally !
Oct 01, 2024 10:02:41 PM lphybeast.LPhyBeastCMD main
SEVERE: LPhyBEAST does not exit normally !
```

Due to the presence of  `E = rmTaxa(names=1:3, alignment=D);` at the end of model block at `jcCoalescent.lphy` file
```
data {
  L = 200;
  taxa = taxa(names=1:10);
}
model {
  Θ ~ LogNormal(meanlog=3.0, sdlog=1.0);
  ψ ~ Coalescent(theta=Θ, taxa=taxa);
  D ~ PhyloCTMC(tree=ψ, L=L, Q=jukesCantor());
  E = rmTaxa(names=1:3, alignment=D);
}
```
though  `E = rmTaxa(names=1:3, alignment=D);` was added via a previous commit [1bfea91](https://github.com/LinguaPhylo/linguaPhylo/commit/1bfea9122fd3ab693bb230bec3dc2a9165f0a829)  under [issue#412](https://github.com/LinguaPhylo/linguaPhylo/issues/412)

removing `E = rmTaxa(names=1:3, alignment=D);` from the model block at `jcCoalescent.lphy` file works fine and generates  5 `XML`, `log` and `nexus` files.

Will removing the `E = rmTaxa(names=1:3, alignment=D);` from `jcCoalescent.lphy` has any further effect on generated XML and future analysis?

**Comment by walterxie** [comment]
Thanks for reporting this bug. The `rmTaxa` cannot map to any BEAST2 objects, so it should be excluded. In LPhyBEAST SPI, there is a method to contain all excluded LPhy generators, `List<Class<? extends Generator>> getExcludedGenerator()`, which cannot map to any BEAST2 objects.

**Comment by walterxie** [comment]
I modified user manual to avoid the confusion before this bug fix is released
