### ISSUE TITLE
make LPhyBEAST as a BEAST 2 package

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#23]
make LPhyBEAST as a BEAST 2 package, so the dependencies can be managed by "Package Manager"

**Comment by walterxie** [comment]
`/Applications/BEAST2.6.3/bin/packagemanager -add lphybeast`

```
    java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at beast.util.PackageManager.doUnzip(Unknown Source)
	at beast.util.PackageManager.installPackages(Unknown Source)
	at beast.util.PackageManager.main(Unknown Source)
```

**Comment by walterxie** [comment]
Manually install:
```bash
ls -l ~/Library/Application\ Support/BEAST/2.6/
mkdir lphybeast
unzip LPhyBEAST.v0.0.2.zip -d ~/Library/Application\ Support/BEAST/2.6/lphybeast/
ls -l ~/Library/Application\ Support/BEAST/2.6/lphybeast
```

**Comment by walterxie** [comment]
This problem has been solved in BEAST 2.
