### ISSUE TITLE
Relaxed clock operators missing IDs

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/LPhyBeast#58]
Running LPhyBeast on linguaPhylo/examples/simpleRelaxedClock.lphy  with the "in development" exception commented out, gives a NullPointerException. The issue appears to be at `lphybeast.BEASTContext.createOperators(BEASTContext.java:789)`

Example script: https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/simpleRelaxedClock.lphy

```
java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because the return value of "java.util.function.Function.apply(Object)" is null
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:221)
	at java.base/java.util.Arrays.sort(Arrays.java:1306)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at lphybeast.BEASTContext.createOperators(BEASTContext.java:789)
```

I have fixed this by assigning IDs to all relaxed clock operators based on the canonical name of the branch rate input https://github.com/LinguaPhylo/LPhyBeast/pull/55
This will produce relaxed clock operator IDs similar to 

```
<operator id="branchRates.model.inConstantDistanceOperator" spec="consoperators.InConstantDistanceOperator" clockModel="@branchRates.model" rates="@branchRates" tree="@tree" twindowSize="0.48984445568209267" weight="11.065045030620489"/>

<operator id="branchRates.model.simpleDistance" spec="consoperators.SimpleDistance" clockModel="@branchRates.model" rates="@branchRates" tree="@tree" twindowSize="0.48984445568209267" weight="1.624504792712471"/>
                        
<operator id="branchRates.model.smallPulley" spec="consoperators.SmallPulley" clockModel="@branchRates.model" dwindowSize="0.1" rates="@branchRates" tree="@tree" weight="1.624504792712471"/>
            
```

**Comment by kche309** [comment]
Comment from @alexeid 
Operator ID should be based on the canonical name from branch rates input, i.e. `phyloCTMC.getBranchRates().getCanonicalId()`

**Comment by kche309** [comment]
My current implementation uses the canonical ID + ".model" suffix for the relaxedClockModel, and an addition ".operatorName" suffix for operators. For example 
```
canonical branch rate = "branchRates"
relaxedClockModel ID = "branchRates.model"
simpleDistanceOperator ID = "branchRates.model.simpleDistance"
smallPulleyOperator ID = "branchRates.model.smallPulley"
```

@kche309 to change operator IDs to match the below format
```
canonical branch rate = "branchRates"
relaxedClockModel ID = "branchRates.model"
simpleDistanceOperator ID = "branchRates.simpleDistance"
smallPulleyOperator ID = "branchRates.smallPulley"
```
