### ISSUE TITLE
morphological data type not working

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#71]
AlignmentToBEAST cannot convert morphological data properly. Run `examples/lewisMKCoalescent.lphy` :

```Java
java.lang.IllegalArgumentException: Could not find code 1101010...00111 in codemap
	at beast.evolution.datatype.DataType$Base.stringToEncoding(Unknown Source)
	at beast.evolution.datatype.DataType$Base.string2state(Unknown Source)
	at beast.evolution.alignment.AlignmentFromTrait.initAndValidate(Unknown Source)
	at lphybeast.tobeast.values.AlignmentToBEAST.valueToBEAST(AlignmentToBEAST.java:62)
	at lphybeast.tobeast.values.AlignmentToBEAST.valueToBEAST(AlignmentToBEAST.java:20)
	at lphybeast.BEASTContext.valueToBEAST(BEASTContext.java:605)
	at lphybeast.BEASTContext.createBEASTValueObjects(BEASTContext.java:518)
```

**Comment by walterxie** [comment]
https://github.com/LinguaPhylo/LPhyBeast/commit/64d8921a0279c7f6e9bede369d05e8c909d39e61
