### ISSUE TITLE
siteRates sampled from DiscretizeGamma cannot create XML

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/LPhyBeast#72]
Load `gtrGammaCoalescent.lphy`:

No coercable parameter found.
```Java
	at lphybeast.BEASTContext.getAsRealParameter(BEASTContext.java:250)
	at lphybeast.tobeast.generators.PhyloCTMCToBEAST.constructSiteModel(PhyloCTMCToBEAST.java:242)
	at lphybeast.tobeast.generators.PhyloCTMCToBEAST.createThreadedTreeLikelihood(PhyloCTMCToBEAST.java:126)
```

**Comment by walterxie** [comment]
`discretizedGamma.getShape()` is not same to the key in `beastObjects` map, so the code `context.getAsRealParameter(discretizedGamma.getShape())` is failed.

**Comment by walterxie** [comment]
It looks `((IID)generator).getBaseDistribution()` returns a different Gamma shape as the `beastObjects` map stored.
